### ISSUE TITLE
signrawtransaction throws struct.error Exception

### ISSUE THREAD

**Issue by elichai** [petertodd/python-bitcoinlib#133]
Hi, when I run this line:
```
rpc = bitcoin.rpc.Proxy()
rpc.signrawtransaction(orig_transaction)
```
I get this exception:
```
Traceback (most recent call last):
  File "PycharmProjects/a.py", line 185, in <module>
    main()
  File "PycharmProjects/a.py", line 160, in main
    r = rpc.signrawtransaction(orig_transaction)
  File "~/.local/lib/python2.7/site-packages/bitcoin/rpc.py", line 630, in signrawtransaction
    hextx = hexlify(tx.serialize())
  File "~/.local/lib/python2.7/site-packages/bitcoin/core/serialize.py", line 102, in serialize
    self.stream_serialize(f)
  File "~/.local/lib/python2.7/site-packages/bitcoin/core/__init__.py", line 336, in stream_serialize
    VectorSerializer.stream_serialize(CTxIn, self.vin, f)
  File "~/.local/lib/python2.7/site-packages/bitcoin/core/serialize.py", line 248, in stream_serialize
    inner_cls.stream_serialize(obj, f)
  File "~/.local/lib/python2.7/site-packages/bitcoin/core/__init__.py", line 206, in stream_serialize
    f.write(struct.pack(b"<I", self.nSequence))
struct.error: cannot convert argument to integer
```

**Comment by elichai** [comment]
Found an Issue my code had with nSequence.
