### ISSUE TITLE
bitcoin.params [bug]?

### ISSUE THREAD

**Issue by cluelessperson** [petertodd/python-bitcoinlib#142]
root@redwood:/etc/znc/modules# cat test.py

import bitcoin.rpc
txid = '55374e78c86bb739c0ef69f92e3f0cfa9b233e293426170c65a2fe381fd54593'
proxy = **bitcoin.rpc.Proxy(btc_conf_file='/etc/znc/bitcoin.conf')**

root@redwood:/etc/znc/modules# python3.5 test.py

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    proxy = bitcoin.rpc.Proxy(btc_conf_file='/etc/znc/bitcoin.conf')
  File "/usr/local/lib/python3.5/dist-packages/bitcoin/rpc.py", line 302, in __init__
    **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/bitcoin/rpc.py", line 157, in __init__
    service_port = **bitcoin.params.RPC_PORT**
**AttributeError: module 'bitcoin' has no attribute 'params'**

---

Params is defined here:
https://github.com/petertodd/python-bitcoinlib/blob/master/bitcoin/__init__.py#L62
but, bitcoin.rpc DOES contain  "import bitcoin"
https://github.com/petertodd/python-bitcoinlib/blob/master/bitcoin/rpc.py#L45

**Comment by adventurist** [comment]
This has been a strange issue for me, as well, affecting me only when doing some tinkering though an interpreter. Does this continue to be an issue for you too?

**Comment by lgdelgadom** [comment]
Having the same problem on macOS, never had that problem on Ubuntu. Where you able to fix it?

**Comment by Gillian217** [comment]
Hi Sir,
Im having the same error in ubuntu version 18
from bitcoin.rpc import RawProxy
>>> p= RawProxy()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.6/site-packages/bitcoin/rpc.py", line 288, in __init__
    **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/bitcoin/rpc.py", line 164, in __init__
    service_port = bitcoin.params.RPC_PORT

i've tried to set a service_port but still encounter an issue 
 p= RawProxy(service_port=8332)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.6/site-packages/bitcoin/rpc.py", line 288, in __init__
    **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/bitcoin/rpc.py", line 172, in __init__
    if bitcoin.params.NAME != "mainnet":
AttributeError: module 'bitcoin' has no attribute 'params'

Hope you can help me.

**Comment by lgdelgadom** [comment]
Sure, I'm using the requests library for python.
Basically this is the template for every rpc you'll do.

`import requests

url = "http://127.0.0.1:8332"
auth = ("user","password")
headers = {"Content-type":"text/plain"}
data = '{"jsonrpc": "2.0", "method": "getblockcount", "id":"0", "params":[]}'

r = requests.post(url, auth=auth, headers=headers, data=data)`

The response is saved in r, you can get the content with r.text or r.content.
This is assuming you are running bitcoind, just change the variables to match your node and the method and parameters for every call you want to make. Hope this helps!

**Comment by Gillian217** [comment]
Hi Sir,
Thank you for your help. I've tried the command and its working perfectly.

**Comment by Gillian217** [comment]
Hi sir,
May I ask if you have been connected to testnet of bitcoin?.
Because I want to try or test transaction of bitcoin or transfer of bitcoin
from one account to another.
Hope you could help me.

**Comment by gigimushroom** [comment]
Same error

**Comment by juxeii** [comment]
Same. Any news on this?

**Comment by summerlove66** [comment]
I got the same problem on  ubuntu 20.04

**Comment by petertodd** [comment]
I wonder if you guys have a different `bitcoin` module installed in your PYTHON_PATH?
