### ISSUE TITLE
cannot create new address from rpc

### ISSUE THREAD

**Issue by DexHunter** [petertodd/python-bitcoinlib#181]
I followed the example

```
proxy = bticoin.rpc.Proxy()
btc = proxy.getnewaddress()
```

but get following error
```
Traceback (most recent call last):
  File "bitswap_protocal.py", line 60, in <module>
    demo()
  File "bitswap_protocal.py", line 36, in demo
    addr_a = proxy.getnewaddress()                 
  File "/home/dex/.conda/envs/hl/lib/python3.6/site-packages/python_bitcoinlib-0.10.2.dev0-py3.6.egg/bitcoin/rpc.py", line 498, in getnewaddress
    return CBitcoinAddress(r)                                    
  File "/home/dex/.conda/envs/hl/lib/python3.6/site-packages/python_bitcoinlib-0.10.2.dev0-py3.6.egg/bitcoin/base58.py", line 105, in __new__
    k = decode(s)
  File "/home/dex/.conda/envs/hl/lib/python3.6/site-packages/python_bitcoinlib-0.10.2.dev0-py3.6.egg/bitcoin/base58.py", line 77, in decode
    raise InvalidBase58Error('Character %r is not a valid base58 character' % c)
bitcoin.base58.InvalidBase58Error: Character ':' is not a valid base58 character
```

It's seems that we cannot give empty input `r` to the `CBitcoinAddress(r)`.

I checked the code https://github.com/petertodd/python-bitcoinlib/blob/05cbb3c9560b36cfe71bac06085a231a6244e13a/bitcoin/base58.py#L106

but I don't quite understand the logic there. Could anyone help? Thanks in advance!

**Comment by DexHunter** [comment]
BTW, I don't have any problems with [this lib](https://github.com/jgarzik/python-bitcoinrpc) when creating new address.

Anyways, since no one replied I am closing this now.
