### ISSUE TITLE
Credentials from configuration file are ignored.

### ISSUE THREAD

**Issue by emmnx** [petertodd/python-bitcoinlib#191]
rpc.py [here](https://github.com/petertodd/python-bitcoinlib/blob/master/bitcoin/rpc.py#L183) states:
`Cookie file unusable (%s) and rpcpassword not specified in the configuration file: %r`
However, rpcpassword and rpcuser are never read from the configuration file. 

This is what I'm getting when trying to use the library:
```
Traceback (most recent call last):
  File "/root/hodl/python-bitcoinlib/bitcoin/rpc.py", line 177, in __init__
    with open(cookie_file, 'r') as fd:
FileNotFoundError: [Errno 2] No such file or directory: '~/.custom_dir/.cookie'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./hodl.py", line 174, in <module>
    args.cmd_func(args)
  File "./hodl.py", line 101, in spend_command
    proxy = bitcoin.rpc.Proxy(btc_conf_file='~/.custom_dir/bitcoin.conf')
  File "/root/hodl/python-bitcoinlib/bitcoin/rpc.py", line 338, in __init__
    **kwargs)
  File "/root/hodl/python-bitcoinlib/bitcoin/rpc.py", line 183, in __init__
    raise ValueError('Cookie file unusable (%s) and rpcpassword not specified in the configuration file: %r' % (err, btc_conf_file))
ValueError: Cookie file unusable ([Errno 2] No such file or directory: '~/.custom_dir/.cookie') and rpcpassword not specified in the configuration file: '~/.custom_dir/bitcoin.conf'
```
Of course `~/.custom_dir/bitcoin.conf` exists, and if I hardcode the credentials at line 167, it works.
Please, help. Thanks in advance.

**Comment by emmnx** [comment]
oh, found the bug, it does not resolve the `~` as home. 
If you specify the full path, it works.
