### ISSUE TITLE
Intermittent `socket.timeout`

### ISSUE THREAD

**Issue by adamkrellenstein** [petertodd/python-bitcoinlib#35]
We're running into a lot of the following errors with our use of python-bitcoinlib in counterpartyd:

```
Traceback (most recent call last):
  File "C:\counterpartyd_build\dist\counterpartyd\counterpartyd.py", line 956, in <module>
    blocks.follow(db)
  File "C:\counterpartyd_build\dist\counterpartyd\lib\blocks.py", line 977, in follow
    mempool_tx_index = list_tx(db, None, block_index, curr_time, tx_hash, mempool_tx_index)
  File "C:\counterpartyd_build\dist\counterpartyd\lib\blocks.py", line 653, in list_tx
    source, destination, btc_amount, fee, data = get_tx_info(tx_dict['hex'], block_index)
  File "C:\counterpartyd_build\dist\counterpartyd\lib\blocks.py", line 341, in get_tx_info
    tx_info = get_tx_info2(tx_hex, block_parser=block_parser)
  File "C:\counterpartyd_build\dist\counterpartyd\lib\blocks.py", line 560, in get_tx_info2
    vin_ctx = proxy.getrawtransaction(vin.prevout.hash)
  File "C:\counterpartyd_build\env\lib\site-packages\bitcoin\rpc.py", line 307, in getrawtransaction
    r = self._call('getrawtransaction', b2lx(txid), 1 if verbose else 0)
  File "C:\counterpartyd_build\env\lib\site-packages\bitcoin\rpc.py", line 144, in _call
    response = self._get_response()
  File "C:\counterpartyd_build\env\lib\site-packages\bitcoin\rpc.py", line 179, in _get_response
    http_response = self.__conn.getresponse()
  File "C:\Python34\Lib\http\client.py", line 1172, in getresponse
    response.begin()
  File "C:\Python34\Lib\http\client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "C:\Python34\Lib\http\client.py", line 313, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Python34\Lib\socket.py", line 371, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
```

Sometimes the problem was being caused by reusing a `Proxy` object, however, AFAIK, we've gotten rid of all of those cases and the error still shows up infrequently and intermittently. Any idea what could be causing this? Is it really the backend taking too long? (I've tried using both Bitcoin Core and btcd.) Should there just be a retry loop somewhere where there isn't? I've also tried `socket.setdefaulttimeout(10)`. Should we be using python-bitcoinlib otherwise? (Should I just be talking to the `socket` or `httplib` teams?

**Comment by miohtama** [comment]
Just for you information if you need thread-safe implementation of `AuthServiceProxy`, I wrote one using threading.local() and you can lift it off from here:

https://bitbucket.org/miohtama/cryptoassets/src/7693fea0cdfb0c0561071e3df15532d33c094bf7/cryptoassets/core/backend/bitcoind.py?at=master#cl-110
